/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LtDrawer {
        "hide": () => Promise<void>;
        "open": boolean;
        "position": 'top' | 'right' | 'bottom' | 'left';
        "show": () => Promise<void>;
    }
    interface LtSidemenu {
        "ariaExpanded": boolean;
        "depth": number;
        "hasChildren": boolean;
        "label": string;
        "parentExpanded": boolean;
        /**
          * Properties **********************
         */
        "url": string;
    }
}
declare global {
    interface HTMLLtDrawerElement extends Components.LtDrawer, HTMLStencilElement {
    }
    var HTMLLtDrawerElement: {
        prototype: HTMLLtDrawerElement;
        new (): HTMLLtDrawerElement;
    };
    interface HTMLLtSidemenuElement extends Components.LtSidemenu, HTMLStencilElement {
    }
    var HTMLLtSidemenuElement: {
        prototype: HTMLLtSidemenuElement;
        new (): HTMLLtSidemenuElement;
    };
    interface HTMLElementTagNameMap {
        "lt-drawer": HTMLLtDrawerElement;
        "lt-sidemenu": HTMLLtSidemenuElement;
    }
}
declare namespace LocalJSX {
    interface LtDrawer {
        "onDrawerAfterHide"?: (event: CustomEvent<any>) => void;
        "onDrawerAfterShow"?: (event: CustomEvent<any>) => void;
        "onDrawerHide"?: (event: CustomEvent<any>) => void;
        "onDrawerOverlayDismiss"?: (event: CustomEvent<any>) => void;
        "onDrawerShow"?: (event: CustomEvent<any>) => void;
        "open"?: boolean;
        "position"?: 'top' | 'right' | 'bottom' | 'left';
    }
    interface LtSidemenu {
        "ariaExpanded"?: boolean;
        "depth"?: number;
        "hasChildren"?: boolean;
        "label"?: string;
        /**
          * Events **********************
         */
        "onMenuItemToggled"?: (event: CustomEvent<any>) => void;
        "parentExpanded"?: boolean;
        /**
          * Properties **********************
         */
        "url"?: string;
    }
    interface IntrinsicElements {
        "lt-drawer": LtDrawer;
        "lt-sidemenu": LtSidemenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lt-drawer": LocalJSX.LtDrawer & JSXBase.HTMLAttributes<HTMLLtDrawerElement>;
            "lt-sidemenu": LocalJSX.LtSidemenu & JSXBase.HTMLAttributes<HTMLLtSidemenuElement>;
        }
    }
}
