/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LtDrawer {
        "hide": () => Promise<void>;
        "open": boolean;
        "position": 'top' | 'right' | 'bottom' | 'left';
        "show": () => Promise<void>;
    }
}
declare global {
    interface HTMLLtDrawerElement extends Components.LtDrawer, HTMLStencilElement {
    }
    var HTMLLtDrawerElement: {
        prototype: HTMLLtDrawerElement;
        new (): HTMLLtDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "lt-drawer": HTMLLtDrawerElement;
    }
}
declare namespace LocalJSX {
    interface LtDrawer {
        "onDrawerHide"?: (event: CustomEvent<any>) => void;
        "onDrawerShow"?: (event: CustomEvent<any>) => void;
        "open"?: boolean;
        "position"?: 'top' | 'right' | 'bottom' | 'left';
    }
    interface IntrinsicElements {
        "lt-drawer": LtDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lt-drawer": LocalJSX.LtDrawer & JSXBase.HTMLAttributes<HTMLLtDrawerElement>;
        }
    }
}
