/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LtDrawer {
        "hide": () => Promise<void>;
        "open": boolean;
        "position": 'top' | 'right' | 'bottom' | 'left';
        "show": () => Promise<void>;
    }
    interface LtModal {
        "hide": () => Promise<void>;
        "modaltitle": string;
        "open": boolean;
        "show": () => Promise<void>;
    }
}
declare global {
    interface HTMLLtDrawerElement extends Components.LtDrawer, HTMLStencilElement {
    }
    var HTMLLtDrawerElement: {
        prototype: HTMLLtDrawerElement;
        new (): HTMLLtDrawerElement;
    };
    interface HTMLLtModalElement extends Components.LtModal, HTMLStencilElement {
    }
    var HTMLLtModalElement: {
        prototype: HTMLLtModalElement;
        new (): HTMLLtModalElement;
    };
    interface HTMLElementTagNameMap {
        "lt-drawer": HTMLLtDrawerElement;
        "lt-modal": HTMLLtModalElement;
    }
}
declare namespace LocalJSX {
    interface LtDrawer {
        "onDrawerAfterHide"?: (event: CustomEvent<any>) => void;
        "onDrawerAfterShow"?: (event: CustomEvent<any>) => void;
        "onDrawerHide"?: (event: CustomEvent<any>) => void;
        "onDrawerOverlayDismiss"?: (event: CustomEvent<any>) => void;
        "onDrawerShow"?: (event: CustomEvent<any>) => void;
        "open"?: boolean;
        "position"?: 'top' | 'right' | 'bottom' | 'left';
    }
    interface LtModal {
        "modaltitle"?: string;
        "onModalAfterHide"?: (event: CustomEvent<any>) => void;
        "onModalAfterShow"?: (event: CustomEvent<any>) => void;
        "onModalHide"?: (event: CustomEvent<any>) => void;
        "onModalOverlayDismiss"?: (event: CustomEvent<any>) => void;
        "onModalShow"?: (event: CustomEvent<any>) => void;
        "open"?: boolean;
    }
    interface IntrinsicElements {
        "lt-drawer": LtDrawer;
        "lt-modal": LtModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lt-drawer": LocalJSX.LtDrawer & JSXBase.HTMLAttributes<HTMLLtDrawerElement>;
            "lt-modal": LocalJSX.LtModal & JSXBase.HTMLAttributes<HTMLLtModalElement>;
        }
    }
}
